[package]
name = "jwt_modes"
version = "0.1.0"
edition = "2021"
description = "A simple RSA and secret key management crate"
license = "MIT"
authors = ["Mohammad Sulaiman <mohammad.sulaiman@exalt.ps>"]
homepage = "https://github.com/MohammadSu1/Authentication_app"
repository = "https://github.com/MohammadSu1/Authentication_app"
keywords = ["secret", "rsa", "jwt", "cryptography"]
categories = ["cryptography", "development-tools::cargo-plugins"]
readme = "README.md"


[dependencies]
jsonwebtoken = "8.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rsa = "0.5"
rand = "0.8"
pem = "1.0"