[package]
name = "jwt_app"
version = "0.1.0"
edition = "2021"

[dependencies]
jsonwebtoken = "8.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rsa = "0.5"
rand = "0.8"
jwt_modes = {path = "./jwt_modes"}
